spring:
  profiles:
    active: Contant


    ##MySQL数据库
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost/hosekeeping?autoReconnect=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

    ##邮件相关配置
  mail:
    host: smtp.qq.com
    port: 465
    username: 773713012@qq.com
    password: qggggbvblxvvbfgi
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true


    ## Redis 配置
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器地址
    host: localhost
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        #spring.redis.pool.max-active=8
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        #spring.redis.pool.max-wait=-1
        max-wait: -1
        ## 连接池中的最大空闲连接
        #spring.redis.pool.max-idle=8
        max-idle: 8
        ## 连接池中的最小空闲连接
        #spring.redis.pool.min-idle=0
        min-idle: 0
    ## 连接超时时间（毫秒）
    timeout: 1200

server:
  port: 8080
  servlet:
    context-path: /housekeeping

##kaptcha
kaptcha:
  border: "no"
  border.color: 0,0,0
  textproducer:
    font:
      color: red
      size: 30
      names: 宋体,楷体,微软雅黑
    char:
      length: 4
  image:
    width: 120
    height: 40
  obscurificator:
    impl: com.google.code.kaptcha.impl.WaterRipple
  session:
    key: code

##jwt密匙
jwt:
  secret: qwerqwerqwerqwerqwerqwerqwerqwer




